import streamlit as st
import json

from data_utils import (
    load_data,
    slice_data,
    dice_data,
    group_and_sum,
    drill_down,
    compare_years,
)

st.set_page_config(page_title="OLAP Assistant ", layout="wide")
st.title("📊 Global Retail OLAP Assistant  — Streamlit")

# Load data (cached)
@st.cache_data
def get_df():
    return load_data()

df = get_df()

st.subheader("Dataset Overview")
st.write(f"Rows: {len(df):,} | Columns: {len(df.columns)}")
st.dataframe(df.head(20), use_container_width=True)

st.divider()
st.subheader("Try OLAP Operations")

op = st.selectbox(
    "Choose operation",
    ["Group & Summarize", "Slice", "Dice", "Drill-Down (Year → Month)", "Compare (Year vs Year)"]
)

if op == "Group & Summarize":
    col1, col2 = st.columns(2)
    with col1:
        group_col = st.selectbox(
            "Group by",
            ["region", "country", "category", "subcategory", "customer_segment", "year", "quarter", "month_name"],
        )
    with col2:
        metric = st.selectbox("Metric", ["revenue", "profit", "quantity", "cost"])

    result = group_and_sum(df, group_col, metric).sort_values(metric, ascending=False)
    st.dataframe(result, use_container_width=True)

    # Chart
    if len(result) > 0:
        st.bar_chart(result.set_index(group_col)[metric])

elif op == "Slice":
    col = st.selectbox(
        "Column",
        ["region", "country", "category", "subcategory", "customer_segment", "year", "quarter", "month_name"],
    )
    values = sorted(df[col].dropna().unique().tolist())
    val = st.selectbox("Value", values)

    result = slice_data(df, col, val)
    st.write(f"Filtered rows: {len(result):,}")
    st.dataframe(result.head(200), use_container_width=True)

elif op == "Dice":
    st.caption("Pick up to 3 filters (leave 'None' to skip).")
    filters = {}

    c1, c2, c3 = st.columns(3)

    with c1:
        col_a = st.selectbox("Filter #1 column", ["None", "region", "category", "year", "quarter", "customer_segment"])
        if col_a != "None":
            val_a = st.selectbox("Filter #1 value", sorted(df[col_a].dropna().unique().tolist()))
            filters[col_a] = val_a

    with c2:
        col_b = st.selectbox("Filter #2 column", ["None", "country", "subcategory", "month_name"])
        if col_b != "None":
            val_b = st.selectbox("Filter #2 value", sorted(df[col_b].dropna().unique().tolist()))
            filters[col_b] = val_b

    with c3:
        col_c = st.selectbox("Filter #3 column", ["None", "region", "category", "year", "customer_segment", "month_name"])
        if col_c != "None":
            val_c = st.selectbox("Filter #3 value", sorted(df[col_c].dropna().unique().tolist()))
            filters[col_c] = val_c

    result = dice_data(df, filters)
    st.write("Filters:", filters if filters else "(none)")
    st.write(f"Filtered rows: {len(result):,}")
    st.dataframe(result.head(200), use_container_width=True)

elif op == "Drill-Down (Year → Month)":
    year = st.selectbox("Year", sorted(df["year"].dropna().unique().tolist()))
    result = drill_down(df, year)

    # Standardize column names for display
    result = result.rename(columns={"month_name": "Month", "revenue": "Revenue"}).sort_values("Revenue", ascending=False)

    st.dataframe(result, use_container_width=True)

    # Chart (Month -> Revenue)
    if len(result) > 0:
        st.bar_chart(result.set_index("Month")["Revenue"])

elif op == "Compare (Year vs Year)":
    years = sorted(df["year"].dropna().unique().tolist())

    col1, col2 = st.columns(2)
    with col1:
        year1 = st.selectbox("Year 1", years, index=0)
    with col2:
        year2 = st.selectbox("Year 2", years, index=min(1, len(years) - 1))

    comp = compare_years(df, year1, year2)

    st.metric(label=f"Revenue {year1}", value=f"{comp['year1']:.2f}")
    st.metric(label=f"Revenue {year2}", value=f"{comp['year2']:.2f}")
    st.metric(label="Difference (Year2 - Year1)", value=f"{comp['difference']:.2f}")

st.divider()
st.subheader("🧠 AI Plan Runner (No API)")

st.caption("Paste a JSON plan (as if it was generated by an LLM), then execute it on the dataset.")

default_plan = {
    "operation": "group",
    "group_by": "region",
    "metric": "revenue",
    "filters": {}
}

plan_text = st.text_area("JSON Plan", value=json.dumps(default_plan, indent=2), height=180)

def execute_plan(plan, df_):
    op_ = plan.get("operation")

    if op_ == "group":
        filtered = dice_data(df_, plan.get("filters", {}))
        out = group_and_sum(filtered, plan.get("group_by"), plan.get("metric"))
        metric_ = plan.get("metric")
        return out.sort_values(metric_, ascending=False)

    if op_ == "slice":
        f = plan.get("filters", {})
        if not f:
            raise ValueError("slice requires filters with 1 key/value")
        k, v = list(f.items())[0]
        return slice_data(df_, k, v)

    if op_ == "dice":
        return dice_data(df_, plan.get("filters", {}))

    if op_ == "drill_down":
        y = plan.get("filters", {}).get("year")
        if y is None:
            raise ValueError("drill_down requires filters.year")
        return drill_down(df_, y)

    if op_ == "compare":
        return compare_years(df_, plan.get("year1"), plan.get("year2"))

    raise ValueError(f"Unknown operation: {op_}")

if st.button("Run Plan"):
    try:
        plan = json.loads(plan_text)
        st.code(json.dumps(plan, indent=2), language="json")
        result = execute_plan(plan, df)

        if isinstance(result, dict):
            st.json(result)
        else:
            st.dataframe(result, use_container_width=True)

    except Exception as e:
        st.error(str(e))



